# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SEEMS.ui'
#
# Created: Sat Feb 20 11:08:14 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys


# Back up the reference to the exceptionhook
sys._excepthook = sys.excepthook


def my_exception_hook(exctype, value, traceback):
    # Print the error and traceback
    print(exctype, value, traceback)
    # Call the normal Exception hook after
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)


# Set the exception hook to our wrapping function
sys.excepthook = my_exception_hook



try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frm_SEEMS_main(object):
    def setupUi(self, frm_SEEMS_main):
        frm_SEEMS_main.setObjectName(_fromUtf8("frm_SEEMS_main"))
        frm_SEEMS_main.resize(1730, 1163)
        self.centralwidget = QWidget(frm_SEEMS_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tab_controlpanel = QTabWidget(self.centralwidget)
        self.tab_controlpanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_controlpanel.setObjectName(_fromUtf8("tab_controlpanel"))
        self.scenarios_manager = QWidget()
        self.scenarios_manager.setObjectName(_fromUtf8("scenarios_manager"))
        self.horizontalLayout_8 = QHBoxLayout(self.scenarios_manager)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gbx_scenario_container = QGroupBox(self.scenarios_manager)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_scenario_container.sizePolicy().hasHeightForWidth())
        self.gbx_scenario_container.setSizePolicy(sizePolicy)
        self.gbx_scenario_container.setMaximumSize(QtCore.QSize(700, 16777215))
        self.gbx_scenario_container.setTitle(_fromUtf8(""))
        self.gbx_scenario_container.setObjectName(_fromUtf8("gbx_scenario_container"))
        self.verticalLayout = QVBoxLayout(self.gbx_scenario_container)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbx_setup_a_scenario = QGroupBox(self.gbx_scenario_container)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_setup_a_scenario.sizePolicy().hasHeightForWidth())
        self.gbx_setup_a_scenario.setSizePolicy(sizePolicy)
        self.gbx_setup_a_scenario.setObjectName(_fromUtf8("gbx_setup_a_scenario"))
        self.verticalLayout_7 = QVBoxLayout(self.gbx_setup_a_scenario)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.formLayout_3 = QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lbl_input_scenario_name = QLabel(self.gbx_setup_a_scenario)
        self.lbl_input_scenario_name.setObjectName(_fromUtf8("lbl_input_scenario_name"))
        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.lbl_input_scenario_name)
        self.txt_input_scenario_name = QLineEdit(self.gbx_setup_a_scenario)
        self.txt_input_scenario_name.setObjectName(_fromUtf8("txt_input_scenario_name"))
        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.txt_input_scenario_name)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.groupBox = QGroupBox(self.gbx_setup_a_scenario)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.rbt_S1_Onsite = QRadioButton(self.groupBox)
        self.rbt_S1_Onsite.setChecked(True)
        self.rbt_S1_Onsite.setObjectName(_fromUtf8("rbt_S1_Onsite"))
        self.horizontalLayout_13.addWidget(self.rbt_S1_Onsite)
        self.rbt_S2_VilGroups = QRadioButton(self.groupBox)
        self.rbt_S2_VilGroups.setObjectName(_fromUtf8("rbt_S2_VilGroups"))
        self.horizontalLayout_13.addWidget(self.rbt_S2_VilGroups)
        self.rbt_S3_Townctrs = QRadioButton(self.groupBox)
        self.rbt_S3_Townctrs.setObjectName(_fromUtf8("rbt_S3_Townctrs"))
        self.horizontalLayout_13.addWidget(self.rbt_S3_Townctrs)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.gbx_set_simulation_period = QGroupBox(self.gbx_setup_a_scenario)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_set_simulation_period.sizePolicy().hasHeightForWidth())
        self.gbx_set_simulation_period.setSizePolicy(sizePolicy)
        self.gbx_set_simulation_period.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gbx_set_simulation_period.setObjectName(_fromUtf8("gbx_set_simulation_period"))
        self.gridLayout_2 = QGridLayout(self.gbx_set_simulation_period)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_set_simulation_start_year = QLabel(self.gbx_set_simulation_period)
        self.lbl_set_simulation_start_year.setObjectName(_fromUtf8("lbl_set_simulation_start_year"))
        self.gridLayout_2.addWidget(self.lbl_set_simulation_start_year, 0, 0, 1, 1)
        self.sbx_set_simulation_start_year = QSpinBox(self.gbx_set_simulation_period)
        self.sbx_set_simulation_start_year.setMaximum(3000)
        self.sbx_set_simulation_start_year.setProperty("value", 2015)
        self.sbx_set_simulation_start_year.setObjectName(_fromUtf8("sbx_set_simulation_start_year"))
        self.gridLayout_2.addWidget(self.sbx_set_simulation_start_year, 0, 1, 1, 1)
        self.lbl_set_simulation_end_year = QLabel(self.gbx_set_simulation_period)
        self.lbl_set_simulation_end_year.setObjectName(_fromUtf8("lbl_set_simulation_end_year"))
        self.gridLayout_2.addWidget(self.lbl_set_simulation_end_year, 0, 2, 1, 1)
        self.sbx_set_simulation_end_year = QSpinBox(self.gbx_set_simulation_period)
        self.sbx_set_simulation_end_year.setMaximum(3000)
        self.sbx_set_simulation_end_year.setProperty("value", 2020)
        self.sbx_set_simulation_end_year.setObjectName(_fromUtf8("sbx_set_simulation_end_year"))
        self.gridLayout_2.addWidget(self.sbx_set_simulation_end_year, 0, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.gbx_set_simulation_period)
        self.gbx_results_saving_options = QGroupBox(self.gbx_setup_a_scenario)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_results_saving_options.sizePolicy().hasHeightForWidth())
        self.gbx_results_saving_options.setSizePolicy(sizePolicy)
        self.gbx_results_saving_options.setObjectName(_fromUtf8("gbx_results_saving_options"))
        self.verticalLayout_6 = QVBoxLayout(self.gbx_results_saving_options)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_save_hh = QLabel(self.gbx_results_saving_options)
        self.lbl_save_hh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_save_hh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_hh.setObjectName(_fromUtf8("lbl_save_hh"))
        self.gridLayout.addWidget(self.lbl_save_hh, 0, 1, 1, 1)
        self.txt_save_hh_interval = QLineEdit(self.gbx_results_saving_options)
        self.txt_save_hh_interval.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_save_hh_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_save_hh_interval.setObjectName(_fromUtf8("txt_save_hh_interval"))
        self.gridLayout.addWidget(self.txt_save_hh_interval, 0, 2, 1, 1)
        self.lbl_save_hh_years = QLabel(self.gbx_results_saving_options)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_save_hh_years.sizePolicy().hasHeightForWidth())
        self.lbl_save_hh_years.setSizePolicy(sizePolicy)
        self.lbl_save_hh_years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_hh_years.setObjectName(_fromUtf8("lbl_save_hh_years"))
        self.gridLayout.addWidget(self.lbl_save_hh_years, 0, 3, 1, 1)
        self.ckb_save_hh_status = QCheckBox(self.gbx_results_saving_options)
        self.ckb_save_hh_status.setEnabled(False)
        self.ckb_save_hh_status.setAcceptDrops(False)
        self.ckb_save_hh_status.setChecked(True)
        self.ckb_save_hh_status.setObjectName(_fromUtf8("ckb_save_hh_status"))
        self.gridLayout.addWidget(self.ckb_save_hh_status, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_save_pp = QLabel(self.gbx_results_saving_options)
        self.lbl_save_pp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_pp.setObjectName(_fromUtf8("lbl_save_pp"))
        self.gridLayout_4.addWidget(self.lbl_save_pp, 0, 1, 1, 1)
        self.txt_save_pp_interval = QLineEdit(self.gbx_results_saving_options)
        self.txt_save_pp_interval.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_save_pp_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_save_pp_interval.setObjectName(_fromUtf8("txt_save_pp_interval"))
        self.gridLayout_4.addWidget(self.txt_save_pp_interval, 0, 2, 1, 1)
        self.lbl_save_pp_years = QLabel(self.gbx_results_saving_options)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_save_pp_years.sizePolicy().hasHeightForWidth())
        self.lbl_save_pp_years.setSizePolicy(sizePolicy)
        self.lbl_save_pp_years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_pp_years.setObjectName(_fromUtf8("lbl_save_pp_years"))
        self.gridLayout_4.addWidget(self.lbl_save_pp_years, 0, 3, 1, 1)
        self.ckb_save_person_status = QCheckBox(self.gbx_results_saving_options)
        self.ckb_save_person_status.setEnabled(False)
        self.ckb_save_person_status.setCheckable(True)
        self.ckb_save_person_status.setChecked(True)
        self.ckb_save_person_status.setObjectName(_fromUtf8("ckb_save_person_status"))
        self.gridLayout_4.addWidget(self.ckb_save_person_status, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.txt_save_land_interval = QLineEdit(self.gbx_results_saving_options)
        self.txt_save_land_interval.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_save_land_interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_save_land_interval.setObjectName(_fromUtf8("txt_save_land_interval"))
        self.gridLayout_5.addWidget(self.txt_save_land_interval, 0, 2, 1, 1)
        self.lbl_save_land = QLabel(self.gbx_results_saving_options)
        self.lbl_save_land.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_land.setObjectName(_fromUtf8("lbl_save_land"))
        self.gridLayout_5.addWidget(self.lbl_save_land, 0, 1, 1, 1)
        self.lbl_save_land_years = QLabel(self.gbx_results_saving_options)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_save_land_years.sizePolicy().hasHeightForWidth())
        self.lbl_save_land_years.setSizePolicy(sizePolicy)
        self.lbl_save_land_years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_save_land_years.setObjectName(_fromUtf8("lbl_save_land_years"))
        self.gridLayout_5.addWidget(self.lbl_save_land_years, 0, 3, 1, 1)
        self.ckb_save_landuse_status = QCheckBox(self.gbx_results_saving_options)
        self.ckb_save_landuse_status.setObjectName(_fromUtf8("ckb_save_landuse_status"))
        self.gridLayout_5.addWidget(self.ckb_save_landuse_status, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.verticalLayout_7.addWidget(self.gbx_results_saving_options)
        self.btn_start_simulation = QPushButton(self.gbx_setup_a_scenario)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_simulation.sizePolicy().hasHeightForWidth())
        self.btn_start_simulation.setSizePolicy(sizePolicy)
        self.btn_start_simulation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_start_simulation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_start_simulation.setObjectName(_fromUtf8("btn_start_simulation"))
        self.verticalLayout_7.addWidget(self.btn_start_simulation)
        self.prb_progressBar = QProgressBar(self.gbx_setup_a_scenario)
        self.prb_progressBar.setProperty("value", 0)
        self.prb_progressBar.setObjectName(_fromUtf8("prb_progressBar"))
        self.verticalLayout_7.addWidget(self.prb_progressBar)
        self.verticalLayout.addWidget(self.gbx_setup_a_scenario)
        spacerItem = QSpacerItem(20, 16777215, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gbx_manage_scenarios = QGroupBox(self.gbx_scenario_container)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_manage_scenarios.sizePolicy().hasHeightForWidth())
        self.gbx_manage_scenarios.setSizePolicy(sizePolicy)
        self.gbx_manage_scenarios.setObjectName(_fromUtf8("gbx_manage_scenarios"))
        self.verticalLayout_5 = QVBoxLayout(self.gbx_manage_scenarios)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_select_manage_scenario = QLabel(self.gbx_manage_scenarios)
        self.lbl_select_manage_scenario.setObjectName(_fromUtf8("lbl_select_manage_scenario"))
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.lbl_select_manage_scenario)
        self.cmb_select_manage_scenario = QComboBox(self.gbx_manage_scenarios)
        self.cmb_select_manage_scenario.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.cmb_select_manage_scenario.setObjectName(_fromUtf8("cmb_select_manage_scenario"))
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.cmb_select_manage_scenario)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btn_rename_scenario = QPushButton(self.gbx_manage_scenarios)
        self.btn_rename_scenario.setObjectName(_fromUtf8("btn_rename_scenario"))
        self.horizontalLayout_7.addWidget(self.btn_rename_scenario)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btn_delete_scenario = QPushButton(self.gbx_manage_scenarios)
        self.btn_delete_scenario.setObjectName(_fromUtf8("btn_delete_scenario"))
        self.horizontalLayout_7.addWidget(self.btn_delete_scenario)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.gbx_manage_scenarios)
        self.horizontalLayout_8.addWidget(self.gbx_scenario_container)
        self.greetings_widget = QWidget(self.scenarios_manager)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greetings_widget.sizePolicy().hasHeightForWidth())
        self.greetings_widget.setSizePolicy(sizePolicy)
        self.greetings_widget.setObjectName(_fromUtf8("greetings_widget"))
        self.horizontalLayout_8.addWidget(self.greetings_widget)
        self.tab_controlpanel.addTab(self.scenarios_manager, _fromUtf8(""))
        self.results_charts = QWidget()
        self.results_charts.setObjectName(_fromUtf8("results_charts"))
        self.horizontalLayout_3 = QHBoxLayout(self.results_charts)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gbx_review_plot_container = QGroupBox(self.results_charts)
        self.gbx_review_plot_container.setMaximumSize(QtCore.QSize(700, 16777215))
        self.gbx_review_plot_container.setTitle(_fromUtf8(""))
        self.gbx_review_plot_container.setObjectName(_fromUtf8("gbx_review_plot_container"))
        self.verticalLayout_9 = QVBoxLayout(self.gbx_review_plot_container)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gpb_select_plot_data_type = QGroupBox(self.gbx_review_plot_container)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpb_select_plot_data_type.sizePolicy().hasHeightForWidth())
        self.gpb_select_plot_data_type.setSizePolicy(sizePolicy)
        self.gpb_select_plot_data_type.setObjectName(_fromUtf8("gpb_select_plot_data_type"))
        self.gridLayout_3 = QGridLayout(self.gpb_select_plot_data_type)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rbt_single_variable_time_series = QRadioButton(self.gpb_select_plot_data_type)
        self.rbt_single_variable_time_series.setObjectName(_fromUtf8("rbt_single_variable_time_series"))
        self.gridLayout_3.addWidget(self.rbt_single_variable_time_series, 0, 0, 1, 1)
        self.rbt_multi_variable_time_series = QRadioButton(self.gpb_select_plot_data_type)
        self.rbt_multi_variable_time_series.setObjectName(_fromUtf8("rbt_multi_variable_time_series"))
        self.gridLayout_3.addWidget(self.rbt_multi_variable_time_series, 0, 1, 1, 1)
        self.rbt_single_variable_cross_section = QRadioButton(self.gpb_select_plot_data_type)
        self.rbt_single_variable_cross_section.setObjectName(_fromUtf8("rbt_single_variable_cross_section"))
        self.gridLayout_3.addWidget(self.rbt_single_variable_cross_section, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.gpb_select_plot_data_type)
        self.gbx_select_plot_scenario_and_variable = QGroupBox(self.gbx_review_plot_container)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_select_plot_scenario_and_variable.sizePolicy().hasHeightForWidth())
        self.gbx_select_plot_scenario_and_variable.setSizePolicy(sizePolicy)
        self.gbx_select_plot_scenario_and_variable.setObjectName(_fromUtf8("gbx_select_plot_scenario_and_variable"))
        self.verticalLayout_2 = QVBoxLayout(self.gbx_select_plot_scenario_and_variable)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_4 = QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lbl_select_review_scenario = QLabel(self.gbx_select_plot_scenario_and_variable)
        self.lbl_select_review_scenario.setObjectName(_fromUtf8("lbl_select_review_scenario"))
        self.formLayout_4.setWidget(0, QFormLayout.LabelRole, self.lbl_select_review_scenario)
        self.cmb_select_review_scenario = QComboBox(self.gbx_select_plot_scenario_and_variable)
        self.cmb_select_review_scenario.setObjectName(_fromUtf8("cmb_select_review_scenario"))
        self.formLayout_4.setWidget(0, QFormLayout.FieldRole, self.cmb_select_review_scenario)
        self.lbl_select_review_variable = QLabel(self.gbx_select_plot_scenario_and_variable)
        self.lbl_select_review_variable.setObjectName(_fromUtf8("lbl_select_review_variable"))
        self.formLayout_4.setWidget(1, QFormLayout.LabelRole, self.lbl_select_review_variable)
        self.cmb_select_review_variable = QComboBox(self.gbx_select_plot_scenario_and_variable)
        self.cmb_select_review_variable.setObjectName(_fromUtf8("cmb_select_review_variable"))
        self.formLayout_4.setWidget(1, QFormLayout.FieldRole, self.cmb_select_review_variable)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.verticalLayout_9.addWidget(self.gbx_select_plot_scenario_and_variable)
        self.gbx_select_plot_period_and_type = QGroupBox(self.gbx_review_plot_container)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_select_plot_period_and_type.sizePolicy().hasHeightForWidth())
        self.gbx_select_plot_period_and_type.setSizePolicy(sizePolicy)
        self.gbx_select_plot_period_and_type.setObjectName(_fromUtf8("gbx_select_plot_period_and_type"))
        self.verticalLayout_3 = QVBoxLayout(self.gbx_select_plot_period_and_type)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gbx_plot_period = QGroupBox(self.gbx_select_plot_period_and_type)
        self.gbx_plot_period.setObjectName(_fromUtf8("gbx_plot_period"))
        self.verticalLayout_11 = QVBoxLayout(self.gbx_plot_period)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_5 = QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lbl_select_plot_start_year = QLabel(self.gbx_plot_period)
        self.lbl_select_plot_start_year.setObjectName(_fromUtf8("lbl_select_plot_start_year"))
        self.formLayout_5.setWidget(0, QFormLayout.LabelRole, self.lbl_select_plot_start_year)
        self.sbx_select_plot_start_year = QSpinBox(self.gbx_plot_period)
        self.sbx_select_plot_start_year.setMaximum(3000)
        self.sbx_select_plot_start_year.setProperty("value", 0)
        self.sbx_select_plot_start_year.setObjectName(_fromUtf8("sbx_select_plot_start_year"))
        self.formLayout_5.setWidget(0, QFormLayout.FieldRole, self.sbx_select_plot_start_year)
        self.horizontalLayout_4.addLayout(self.formLayout_5)
        self.formLayout_6 = QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.lbl_select_plot_end_year = QLabel(self.gbx_plot_period)
        self.lbl_select_plot_end_year.setObjectName(_fromUtf8("lbl_select_plot_end_year"))
        self.formLayout_6.setWidget(0, QFormLayout.LabelRole, self.lbl_select_plot_end_year)
        self.sbx_select_plot_end_year = QSpinBox(self.gbx_plot_period)
        self.sbx_select_plot_end_year.setMaximum(3000)
        self.sbx_select_plot_end_year.setProperty("value", 0)
        self.sbx_select_plot_end_year.setObjectName(_fromUtf8("sbx_select_plot_end_year"))
        self.formLayout_6.setWidget(0, QFormLayout.FieldRole, self.sbx_select_plot_end_year)
        self.horizontalLayout_4.addLayout(self.formLayout_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.gbx_plot_period)
        self.gbx_plot_type = QGroupBox(self.gbx_select_plot_period_and_type)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_plot_type.sizePolicy().hasHeightForWidth())
        self.gbx_plot_type.setSizePolicy(sizePolicy)
        self.gbx_plot_type.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gbx_plot_type.setObjectName(_fromUtf8("gbx_plot_type"))
        self.horizontalLayout_2 = QHBoxLayout(self.gbx_plot_type)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbt_bar_chart = QRadioButton(self.gbx_plot_type)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbt_bar_chart.sizePolicy().hasHeightForWidth())
        self.rbt_bar_chart.setSizePolicy(sizePolicy)
        self.rbt_bar_chart.setObjectName(_fromUtf8("rbt_bar_chart"))
        self.horizontalLayout_2.addWidget(self.rbt_bar_chart)
        self.rbt_line_chart = QRadioButton(self.gbx_plot_type)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbt_line_chart.sizePolicy().hasHeightForWidth())
        self.rbt_line_chart.setSizePolicy(sizePolicy)
        self.rbt_line_chart.setObjectName(_fromUtf8("rbt_line_chart"))
        self.horizontalLayout_2.addWidget(self.rbt_line_chart)
        self.rbt_histogram = QRadioButton(self.gbx_plot_type)
        self.rbt_histogram.setObjectName(_fromUtf8("rbt_histogram"))
        self.horizontalLayout_2.addWidget(self.rbt_histogram)
        self.verticalLayout_3.addWidget(self.gbx_plot_type)
        self.verticalLayout_9.addWidget(self.gbx_select_plot_period_and_type)
        spacerItem2 = QSpacerItem(20, 16777215, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.btn_review_plot = QPushButton(self.gbx_review_plot_container)
        self.btn_review_plot.setObjectName(_fromUtf8("btn_review_plot"))
        self.verticalLayout_9.addWidget(self.btn_review_plot)
        self.horizontalLayout_3.addWidget(self.gbx_review_plot_container)
        self.canvas_widget = QWidget(self.results_charts)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas_widget.sizePolicy().hasHeightForWidth())
        self.canvas_widget.setSizePolicy(sizePolicy)
        self.canvas_widget.setObjectName(_fromUtf8("canvas_widget"))
        self.horizontalLayout_3.addWidget(self.canvas_widget)
        self.tab_controlpanel.addTab(self.results_charts, _fromUtf8(""))
        self.results_maps = QWidget()
        self.results_maps.setObjectName(_fromUtf8("results_maps"))
        self.horizontalLayout_6 = QHBoxLayout(self.results_maps)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gbx_map_container = QGroupBox(self.results_maps)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_map_container.sizePolicy().hasHeightForWidth())
        self.gbx_map_container.setSizePolicy(sizePolicy)
        self.gbx_map_container.setMaximumSize(QtCore.QSize(700, 16777215))
        self.gbx_map_container.setTitle(_fromUtf8(""))
        self.gbx_map_container.setObjectName(_fromUtf8("gbx_map_container"))
        self.verticalLayout_4 = QVBoxLayout(self.gbx_map_container)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gpb_map_settings = QGroupBox(self.gbx_map_container)
        self.gpb_map_settings.setObjectName(_fromUtf8("gpb_map_settings"))
        self.verticalLayout_8 = QVBoxLayout(self.gpb_map_settings)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.formLayout_10 = QFormLayout()
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.lbl_select_map_scenario = QLabel(self.gpb_map_settings)
        self.lbl_select_map_scenario.setObjectName(_fromUtf8("lbl_select_map_scenario"))
        self.formLayout_10.setWidget(0, QFormLayout.LabelRole, self.lbl_select_map_scenario)
        self.cmb_select_map_scenario = QComboBox(self.gpb_map_settings)
        self.cmb_select_map_scenario.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.cmb_select_map_scenario.setObjectName(_fromUtf8("cmb_select_map_scenario"))
        self.formLayout_10.setWidget(0, QFormLayout.FieldRole, self.cmb_select_map_scenario)
        self.lbl_select_map_layer = QLabel(self.gpb_map_settings)
        self.lbl_select_map_layer.setObjectName(_fromUtf8("lbl_select_map_layer"))
        self.formLayout_10.setWidget(1, QFormLayout.LabelRole, self.lbl_select_map_layer)
        self.cmb_select_map_layer = QComboBox(self.gpb_map_settings)
        self.cmb_select_map_layer.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.cmb_select_map_layer.setObjectName(_fromUtf8("cmb_select_map_layer"))
        self.formLayout_10.setWidget(1, QFormLayout.FieldRole, self.cmb_select_map_layer)
        self.verticalLayout_8.addLayout(self.formLayout_10)
        self.formLayout_2 = QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_select_map_year = QLabel(self.gpb_map_settings)
        self.lbl_select_map_year.setObjectName(_fromUtf8("lbl_select_map_year"))
        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.lbl_select_map_year)
        self.lbl_map_current_year = QLabel(self.gpb_map_settings)
        self.lbl_map_current_year.setText(_fromUtf8(""))
        self.lbl_map_current_year.setObjectName(_fromUtf8("lbl_map_current_year"))
        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.lbl_map_current_year)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.sld_select_map_year = QSlider(self.gpb_map_settings)
        self.sld_select_map_year.setOrientation(QtCore.Qt.Horizontal)
        self.sld_select_map_year.setTickPosition(QSlider.TicksBelow)
        self.sld_select_map_year.setObjectName(_fromUtf8("sld_select_map_year"))
        self.verticalLayout_8.addWidget(self.sld_select_map_year)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_map_start_year = QLabel(self.gpb_map_settings)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_map_start_year.sizePolicy().hasHeightForWidth())
        self.lbl_map_start_year.setSizePolicy(sizePolicy)
        self.lbl_map_start_year.setText(_fromUtf8(""))
        self.lbl_map_start_year.setObjectName(_fromUtf8("lbl_map_start_year"))
        self.horizontalLayout_5.addWidget(self.lbl_map_start_year)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lbl_map_end_year = QLabel(self.gpb_map_settings)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_map_end_year.sizePolicy().hasHeightForWidth())
        self.lbl_map_end_year.setSizePolicy(sizePolicy)
        self.lbl_map_end_year.setText(_fromUtf8(""))
        self.lbl_map_end_year.setObjectName(_fromUtf8("lbl_map_end_year"))
        self.horizontalLayout_5.addWidget(self.lbl_map_end_year)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.gpb_map_settings)
        spacerItem4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.btn_show_map = QPushButton(self.gbx_map_container)
        self.btn_show_map.setObjectName(_fromUtf8("btn_show_map"))
        self.verticalLayout_4.addWidget(self.btn_show_map)
        self.horizontalLayout_6.addWidget(self.gbx_map_container)
        self.map_display_widget = QWidget(self.results_maps)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_display_widget.sizePolicy().hasHeightForWidth())
        self.map_display_widget.setSizePolicy(sizePolicy)
        self.map_display_widget.setObjectName(_fromUtf8("map_display_widget"))
        self.horizontalLayout_6.addWidget(self.map_display_widget)
        self.tab_controlpanel.addTab(self.results_maps, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tab_controlpanel)
        frm_SEEMS_main.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(frm_SEEMS_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1730, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        frm_SEEMS_main.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(frm_SEEMS_main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frm_SEEMS_main.setStatusBar(self.statusbar)
        self.actionAbout = QAction(frm_SEEMS_main)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(frm_SEEMS_main)
        self.tab_controlpanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frm_SEEMS_main)

    def retranslateUi(self, frm_SEEMS_main):
        frm_SEEMS_main.setWindowTitle(_translate("frm_SEEMS_main", "SEEMS  -  Socio-Econ-Ecosystem Multipurpose Simulator", None))
        self.gbx_setup_a_scenario.setTitle(_translate("frm_SEEMS_main", "Setup a New Scenario", None))
        self.lbl_input_scenario_name.setText(_translate("frm_SEEMS_main", "Scenario Name:", None))
        self.groupBox.setTitle(_translate("frm_SEEMS_main", "Post-Earthquake Restoration Options", None))
        self.rbt_S1_Onsite.setText(_translate("frm_SEEMS_main", "On Site", None))
        self.rbt_S2_VilGroups.setText(_translate("frm_SEEMS_main", "To Village Groups", None))
        self.rbt_S3_Townctrs.setText(_translate("frm_SEEMS_main", "To Township Centers", None))
        self.gbx_set_simulation_period.setTitle(_translate("frm_SEEMS_main", "Set Simulation Period", None))
        self.lbl_set_simulation_start_year.setText(_translate("frm_SEEMS_main", "Start Year:", None))
        self.lbl_set_simulation_end_year.setText(_translate("frm_SEEMS_main", "End Year:", None))
        self.gbx_results_saving_options.setTitle(_translate("frm_SEEMS_main", "Results Saving Options", None))
        self.lbl_save_hh.setText(_translate("frm_SEEMS_main", " Every", None))
        self.txt_save_hh_interval.setText(_translate("frm_SEEMS_main", "1", None))
        self.lbl_save_hh_years.setText(_translate("frm_SEEMS_main", "Year(s)", None))
        self.ckb_save_hh_status.setText(_translate("frm_SEEMS_main", "Save Household Status", None))
        self.lbl_save_pp.setText(_translate("frm_SEEMS_main", " Every", None))
        self.txt_save_pp_interval.setText(_translate("frm_SEEMS_main", "1", None))
        self.lbl_save_pp_years.setText(_translate("frm_SEEMS_main", "Year(s)", None))
        self.ckb_save_person_status.setText(_translate("frm_SEEMS_main", "Save Person Status", None))
        self.txt_save_land_interval.setText(_translate("frm_SEEMS_main", "4", None))
        self.lbl_save_land.setText(_translate("frm_SEEMS_main", " Every", None))
        self.lbl_save_land_years.setText(_translate("frm_SEEMS_main", "Year(s)", None))
        self.ckb_save_landuse_status.setText(_translate("frm_SEEMS_main", "Save LandUse Status", None))
        self.btn_start_simulation.setText(_translate("frm_SEEMS_main", "Start Simulation", None))
        self.gbx_manage_scenarios.setTitle(_translate("frm_SEEMS_main", "Manage Scenarios", None))
        self.lbl_select_manage_scenario.setText(_translate("frm_SEEMS_main", "Select Scenario:", None))
        self.btn_rename_scenario.setText(_translate("frm_SEEMS_main", "Rename", None))
        self.btn_delete_scenario.setText(_translate("frm_SEEMS_main", "Delete", None))
        self.tab_controlpanel.setTabText(self.tab_controlpanel.indexOf(self.scenarios_manager), _translate("frm_SEEMS_main", "Scenarios Manager", None))
        self.gpb_select_plot_data_type.setTitle(_translate("frm_SEEMS_main", "Plot Data Type", None))
        self.rbt_single_variable_time_series.setText(_translate("frm_SEEMS_main", "Single Variable Time Series", None))
        self.rbt_multi_variable_time_series.setText(_translate("frm_SEEMS_main", "Multi Variable Time Series", None))
        self.rbt_single_variable_cross_section.setText(_translate("frm_SEEMS_main", "Single Variable Cross Section", None))
        self.gbx_select_plot_scenario_and_variable.setTitle(_translate("frm_SEEMS_main", "Scenario and Variable", None))
        self.lbl_select_review_scenario.setText(_translate("frm_SEEMS_main", "Select Scenario:", None))
        self.lbl_select_review_variable.setText(_translate("frm_SEEMS_main", "Select Variable:", None))
        self.gbx_select_plot_period_and_type.setTitle(_translate("frm_SEEMS_main", "Plot Period and Type", None))
        self.gbx_plot_period.setTitle(_translate("frm_SEEMS_main", "Plot Period", None))
        self.lbl_select_plot_start_year.setText(_translate("frm_SEEMS_main", "Select Start Year:", None))
        self.lbl_select_plot_end_year.setText(_translate("frm_SEEMS_main", "Select End Year:", None))
        self.gbx_plot_type.setTitle(_translate("frm_SEEMS_main", "Plot Type", None))
        self.rbt_bar_chart.setText(_translate("frm_SEEMS_main", "(Stacked) Bars", None))
        self.rbt_line_chart.setText(_translate("frm_SEEMS_main", "(Multiple) Lines", None))
        self.rbt_histogram.setText(_translate("frm_SEEMS_main", "Histogram", None))
        self.btn_review_plot.setText(_translate("frm_SEEMS_main", "Plot", None))
        self.tab_controlpanel.setTabText(self.tab_controlpanel.indexOf(self.results_charts), _translate("frm_SEEMS_main", "Results - Charts", None))
        self.gpb_map_settings.setTitle(_translate("frm_SEEMS_main", "Map Settings", None))
        self.lbl_select_map_scenario.setText(_translate("frm_SEEMS_main", "Select Scenario:", None))
        self.lbl_select_map_layer.setText(_translate("frm_SEEMS_main", "Select Map Layer:", None))
        self.lbl_select_map_year.setText(_translate("frm_SEEMS_main", "Select Map Year:", None))
        self.btn_show_map.setText(_translate("frm_SEEMS_main", "Show Map", None))
        self.tab_controlpanel.setTabText(self.tab_controlpanel.indexOf(self.results_maps), _translate("frm_SEEMS_main", "Results - Maps", None))
        self.menuHelp.setTitle(_translate("frm_SEEMS_main", "Help", None))
        self.actionAbout.setText(_translate("frm_SEEMS_main", "About", None))


# Main
if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui=Ui_frm_SEEMS_main()
    main=QMainWindow()
    ui.setupUi(main)


    main.show()
    app.exec_()


